### ISSUE TITLE
redirect: add redirect for gonum.org/v1/exp/...

### ISSUE THREAD

**Issue by sbinet** [gonum/old-website#20]

**Comment by btracey** [comment]
Do we want this (genuinely unsure)? My view of `exp` is as a location for development of packages we plan to move into `gonum` (or another 'full' package). The lack of a vanity import clearly shows the second class status, and I don't think we want to have support indefinitely.

**Comment by sbinet** [comment]
`linsolve` and `rings` *already* use the vanity imports.
it seems silly to require people wanting to test these experimental packages to install them like so:
```
$> cd $GOPATH/src
$> git clone git@github.com:gonum/exp gonum.org/v1/exp
$> go install gonum.org/v1/exp/...
```

instead of the usual `go get gonum.org/v1/exp/...`.

the `.travis.yml` CI is also installing+testing them as `gonum.org/v1/exp`.

that said, I am ok with just reverting all these and just installing them as `github.com/gonum/exp`.
but we need to be consistent.

**Comment by btracey** [comment]
Sorry, I forgot that we have the vanity imports for those (maybe we've even already had this discussion?) I agree with being consistent.
