### ISSUE TITLE
https isn't loading properly

### ISSUE THREAD

**Issue by btracey** [gonum/old-website#3]
A lot of the icons don't load properly from https://www.gonum.org/, and navigating switches from https to http. See https://www.reddit.com/r/golang/comments/70mnfi/new_hugobased_website_for_gonum/dn4cc6b/

I think this is an academic theme issue. Going to https://kortschak.io/ or https://gopherdata.io/ gives me "connection not private" errors on both firefox and chrome (os x). I have no idea why gonum.org is fine for the connection not private errors, though we have other issues.

**Comment by btracey** [comment]
@dwhitena

**Comment by btracey** [comment]
This may also be a netlify thing, they have some https stuff there.

**Comment by kortschak** [comment]
kortschak.io [is not configured to serve https](https://github.com/kortschak/kortschak.io/blob/49c2cef8678026bf807e38428ef38622e5f0dfa2/config.toml#L1) and/because I don't have an SSL cert.

**Comment by btracey** [comment]
Okay, the good news is I was able to get the https certification working.

**Comment by kortschak** [comment]
For future reference, what was the issue?

**Comment by btracey** [comment]
Oh, sorry, meant to say that.

I switched to the Netlify DNS resolver, and got a certificate from them. I'm not convinced it's working properly yet though, because navigating around in https seems to have issues.

**Comment by btracey** [comment]
Apparently the certifications can take up to 24 hours to activate, so that may be the issue.

**Comment by dwhitena** [comment]
Hey! Yeah, I really need to fix this on gopherdata.io as well. I will be interested in seeing the fix here. I am hosting on Github pages, and need to switch I think.
